[package]
name = "scream"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.3", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
microbit-v2 = "0.13.0"

panic-halt = "0.2.0"
defmt-rtt = "0.4"
defmt = "0.3.1"

lsm303agr = "0.2.2"